baseURL = "https://zevdg.com"
languageCode = "en-us"
title = "zevdg"

theme = "beautifulhugo"

[Params]
  homeTitle = "Blog"
  subtitle = "Musings on Software Development, User Experience, and Life"
  favicon = "img/favicon.ico"

[Author]
  name = "Zev Goldstein"
  email = "Zev.Goldstein@gmail.com"
  linkedin = "zevdg"
  reddit = "zevdg"
  github = "zevdg"

[menu]
  [[menu.main]]
    name = "About Me"
    url = "page/about-me/"
    weight = 3